server:
  port: 9092
  
# 뷰 페이지
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource: # 마이바티스 dataSource객체 세팅
    driver-class-name: 
    url: jdbc:mysql://localhost:3306/campusdb?characterEncoding=utf-8
    username: root
    password: 1234
      
  devtools: # 코드 수정시 서버 자동 재시작
    livereload:
      enabled: true

mybatis: # mybatis mapper에서 returnType 속성에 패키지 생략 할 수 있도록 설정
  type-aliases-package: com.campus.myapp.vo
  mapper-locations: mapper/*Mapper.xml